<?php

namespace MWAssistant;

use MediaWiki\MediaWikiServices;
use MediaWiki\Config\Config as MWConfig;
use RuntimeException;

/**
 * Centralized configuration accessor for the MWAssistant extension.
 *
 * Wraps MediaWiki's main configuration and provides:
 *   - Strict typed accessors
 *   - Validation of required secrets
 *   - Optional default values where reasonable
 *
 * Configuration keys MUST be defined in extension.json and/or LocalSettings.php
 * for predictable behavior.
 */
class Config
{

    /** @var MWConfig|null Cached reference to MediaWiki's main config */
    private static ?MWConfig $mainConfig = null;

    /**
     * Internal helper to obtain MW MainConfig only once.
     */
    private static function cfg(): MWConfig
    {
        if (self::$mainConfig === null) {
            self::$mainConfig = MediaWikiServices::getInstance()->getMainConfig();
        }
        return self::$mainConfig;
    }

    // -------------------------------------------------------------------------
    // Core MCP API Settings
    // -------------------------------------------------------------------------

    /**
     * Base URL for the MCP server (e.g., https://127.0.0.1:8123).
     *
     * @return string
     */
    public static function getMCPBaseUrl(): string
    {
        $url = self::cfg()->get('MWAssistantMCPBaseUrl');

        if (!is_string($url) || trim($url) === '') {
            throw new RuntimeException(
                'MWAssistant: MWAssistantMCPBaseUrl must be configured in LocalSettings.php'
            );
        }

        return rtrim($url, '/');
    }

    // -------------------------------------------------------------------------
    // JWT Secrets (Required)
    // -------------------------------------------------------------------------

    /**
     * Secret key for JWTs generated by MediaWiki → MCP.
     *
     * @return string Non-empty secret
     */
    public static function getJWTMWToMCPSecret(): string
    {
        return self::requireNonEmptyString(
            self::cfg()->get('MWAssistantJWTMWToMCPSecret'),
            'MWAssistantJWTMWToMCPSecret'
        );
    }

    /**
     * Secret key for JWTs generated by MCP → MediaWiki.
     *
     * @return string Non-empty secret
     */
    public static function getJWTMCPToMWSecret(): string
    {
        return self::requireNonEmptyString(
            self::cfg()->get('MWAssistantJWTMCPToMWSecret'),
            'MWAssistantJWTMCPToMWSecret'
        );
    }

    // -------------------------------------------------------------------------
    // Feature Flags and Behavior Controls
    // -------------------------------------------------------------------------

    /**
     * Whether MWAssistant is globally enabled.
     *
     * @return bool
     */
    public static function isEnabled(): bool
    {
        return (bool) self::cfg()->get('MWAssistantEnabled');
    }

    /**
     * TTL (seconds) for JWTs generated by MediaWiki for MCP calls.
     *
     * Must be a positive integer, typically 30–120 seconds.
     *
     * @return int
     */
    public static function getJWTTTL(): int
    {
        $ttl = self::cfg()->get('MWAssistantJWTTTL');

        if (!is_int($ttl) || $ttl <= 0) {
            throw new RuntimeException(
                'MWAssistant: MWAssistantJWTTTL must be a positive integer (seconds)'
            );
        }

        return $ttl;
    }

    /**
     * Whether automatic embedding updates are enabled.
     *
     * @return bool
     */
    public static function isAutoEmbedEnabled(): bool
    {
        return (bool) self::cfg()->get('MWAssistantAutoEmbed');
    }

    // -------------------------------------------------------------------------
    // Validation Helpers
    // -------------------------------------------------------------------------

    /**
     * Validates that a config value is a non-empty string.
     *
     * @param mixed $value
     * @param string $keyName Configuration key name for error reporting
     * @return string
     */
    private static function requireNonEmptyString(mixed $value, string $keyName): string
    {
        if (!is_string($value) || trim($value) === '') {
            throw new RuntimeException(
                "MWAssistant: {$keyName} must be configured in LocalSettings.php"
            );
        }
        return $value;
    }
}
